# Generated by Django 3.1.7 on 2021-05-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20210510_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='multi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='prop',
            field=models.ManyToManyField(null=True, related_name='question', to='question.Proposition'),
        ),
    ]
