# Generated by Django 3.1.7 on 2021-05-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20210510_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='titre',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
