# Generated by Django 3.1.7 on 2021-05-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_question_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='prop',
            field=models.ManyToManyField(blank=True, null=True, related_name='question', to='question.Proposition'),
        ),
    ]
